repos:
- repo: local
  hooks:
  - id: black
    args: [--line-length=100]
    name: black
    stages: [commit]
    language: system
    entry: pipenv run black
    types: [python]
  - id: flake8
    name: flake8
    stages: [commit]
    language: system
    entry: pipenv run flake8
    types: [python]
  - id: mypy
    name: mypy
    stages: [commit]
    language: system
    entry: pipenv run mypy --ignore-missing-imports
    types: [python]
    pass_filenames: false
    verbose: true
