version: "1"
services:
  local-db:
    container_name: local-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    image: library/postgres:latest
    ports:
      - 5448:5432/tcp
    expose:
      - "5448"
    env_file:
      - ".env"
  test-db:
    image: library/postgres:latest
    container_name: test-db
    ports:
      - 5445:5432/tcp
    expose:
      - "5445"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
volumes:
  redis: {}
  data: